/* select limit */
USE COUNTRIES;
SELECT COUNTRY_ID FROM countries;
SELECT COUNTRY_ID FROM countries LIMIT 10;
--  RETURN FROM 10TH ROW PRINT NEXT 10 ROW
SELECT COUNTRY_ID FROM countries LIMIT 10,10;
-- RETURNS LAST 2 ROW
SELECT COUNTRY_ID FROM countries 
ORDER BY COUNTRY_ID DESC LIMIT 2;