/*
select column(s)
from table
order by column ASC|DESC  
*/
-- DEFAULT ASENDING
SELECT * 
FROM COUNTRIES.COUNTRIES 
ORDER BY REGION_ID;
-- desc
SELECT * 
FROM COUNTRIES.COUNTRIES 
ORDER BY REGION_ID DESC;
-- ORDER BY WITH MULTIPLE COLUMNS
SELECT REGION_ID,COUNTRY_ID
FROM COUNTRIES.COUNTRIES 
order by REGION_ID ASC,COUNTRY_ID DESC;